# tempo-distributed - Chart: 1.9.11, App Version: 2.4.2

metricsGenerator:
  enabled: true
  replicas: 2
  config:
    storage:
      remote_write: 
        - url: http://tracing-prometheus-server.observability.svc.cluster.local:80/api/v1/write

traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

global_overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
